### ISSUE TITLE
Add botan.io integration 

### ISSUE THREAD

**Issue by danog** [pwrtelegram/pwrtelegram#1]
I was thinking of integratung botan.io analytics in the API (as an optional feature of course).
What do you think?
Is it a good idea? Let me know.

**Comment by TiagoDanin** [comment]
Great idea.

**Comment by MarcoBuster** [comment]
Yes, great idea

**Comment by saturn99** [comment]
Yes,it's good,
+1

**Comment by LucasGorgal** [comment]
It was shutdown
