### ISSUE TITLE
Add a new method for detecting client's language

### ISSUE THREAD

**Issue by veetaw** [pwrtelegram/pwrtelegram#18]
pls <3

**Comment by giuseppelagaipa** [comment]
@veetaw

**Comment by wrxck** [comment]
Not sure this is even possible without prior user authentication

**Comment by danog** [comment]
You can now do this

**Comment by MarcoBuster** [comment]
@danog How?

**Comment by danog** [comment]
@MarcoBuster To fetch the language code of a certain user run the getChat method providing the users username or id as parameter, the result will be present in the lang_code field: https://daniil.it/MadelineProto/Chat.html

**Comment by MarcoBuster** [comment]
@danog Thanks! This works in the main API (not beta), too?

**Comment by danog** [comment]
@MarcoBuster Yep, it works in the main pwrtelegram endpoint too.

**Comment by MarcoBuster** [comment]
@danog Awesome!
