### ISSUE TITLE
getMessage doesn't work on channels

### ISSUE THREAD

**Issue by par6n** [pwrtelegram/pwrtelegram#22]
Title is saying it. When I try to `getMessage` a message from a channel, I get this error:
```{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}```

But the chat_id exists (Used it to send a message to the channel) and the bot is one of the admins of the channel.

**Comment by danog** [comment]
That is weird, could you please pm telegram.me/danogentili for more details?

**Comment by wrxck** [comment]
cough t.me
