### ISSUE TITLE
Attempting to call messages.setTyping results in an error

### ISSUE THREAD

**Issue by kamikazechaser** [pwrtelegram/pwrtelegram#27]
Attempting to call `messages.setTyping` for a user bot results in an error:

```js
{
   ok: false
   error_code: 400
   description: "Predicate was not set! on line 191 of TL.php"
}
```

This is my `GET` request:

`https://api.pwrtelegram.xyz/user135207785:XXXXXXXXXXX/messages.setTyping?peer=135207785&action=sendMessageTypingAction`

**Comment by danog** [comment]
`https://api.pwrtelegram.xyz/user135207785:XXXXXXXXXXX/messages.setTyping?peer=135207785&action={"_":"sendMessageTypingAction"}`
This is the correct syntax.
