### ISSUE TITLE
Webhook POST request is empty

### ISSUE THREAD

**Issue by kamikazechaser** [pwrtelegram/pwrtelegram#29]
user API seems to send an empty body in the POST request. Reproduced steps:

1: Set webhook

`https://api.pwrtelegram.xyz/userXXXXXXXXX/setWebHook?url=https://XXXXXXXXX/tguser`

2: Handle POST requests with an express server:

```js
const bodyParser = require("body-parser");
const express = require("express");

app.use(bodyParser.json());

app.post("/tguser", (req, res) => {
    console.log(req.body);
})

app.listen(80, () => {
    console.log("Server started!");
});
```

3: Empty response

`{}`

POST requests come through but the problem could be server side serializing to JSON of the updates.

**Comment by danog** [comment]
It's probably more issues with JSON serialization of updates server-side, due to non-utf8 chars

**Comment by kamikazechaser** [comment]
Issue seemed to be the parsing, using ```app.use(bodyParser.urlencoded({ extended: false }));``` instead of ```app.use(bodyParser.json());``` solved it!

**Comment by danog** [comment]
You can now use .json(), I've set the content type to application/json
