### ISSUE TITLE
error in download file

### ISSUE THREAD

**Issue by BluestarCo** [pwrtelegram/pwrtelegram#31]
hi gusy i have problem in  download file
 i can get file info and file path

{"ok":true,"result":{"file_id":"BQADBAADlgADUUSYUO1aLFRjDtdnAg","file_path":"391993836\/document\/codecanyon-10771397-android-news-app_5807466834177294486.zip","file_size":64518027}}

but when download it from this url  https://storage.pwrtelegram.xyz/391993836/document/codecanyon-10771397-android-news-app_5807466834177294486.zip

i got this error

500 internal server error

SESSION_REVOKED on line 338 of ResponseHandler.php

how to resolve this?

**Comment by danog** [comment]
@amirhododi You have revoked your token, right?
