### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by saturn99** [pwrtelegram/pwrtelegram#33]
i open this url with my phone number:
```https://api.pwrtelegram.xyz/phonelogin?phone=+989********3```

and give error:
```{"ok":false,"error_code":429,"description":"Too Many Requests: retry after 86400","params":{"retry_after":"86400"}}```

**Comment by danog** [comment]
Someone is using the API to bruteforce phone numbers. That's the reason for these constant rate limitations on logins
