### ISSUE TITLE
Could not find method: addchatuser

### ISSUE THREAD

**Issue by klke** [pwrtelegram/pwrtelegram#35]
Hi, iam not able to got addchatuser method working, iam getting this error:

{"ok":false,"error_code":400,"description":"Could not find method: addchatuser on line 393 of TL.php"}

And this is the call that i made:
https://api.pwrtelegram.xyz/user28xxxx:xxxxxxxxxxxxxxx/addchatuser?chat_id=@xxxx&user_id=@xxxx&forward_limit=2147483647

When i do as a bot i get:
{"ok":false,"error_code":400,"description":"Provided value 10xxxxxxx is bigger than 2147483647 on line 84 of Tools.php"}

As far as i know as a bot its imposible due to a limitation that just allow bots to invite to normal chats not groups, but what iam doing wrong with user addchatuser method?

Any help is appreciated, many thanks

**Comment by danog** [comment]
That is not the method that should be used as a user. Please read daniil.it/MadelineProto, pwrtelegram.xyz, daniil.it/MadelineProto/API_docs
