### ISSUE TITLE
error server not found in download link

### ISSUE THREAD

**Issue by ghasemy50** [pwrtelegram/pwrtelegram#40]
hi , i have problem in download file
i can get file info and file path

{"ok":true,"result":{"file_id":"BQADBAADkwEAArQwKFFDOIk1siZUcgI","file_path":"429742403\/document\/iusteduc_store_5847977665792835987.sql","file_size":131754}}

but when download it from this url https://storage.pwrtelegram.xyz/429742403/document/iusteduc_store_5847977665792835987.sql

i got this error in mozilla firefox:

Server not found

Firefox can’t find the server at storage.pwrtelegram.xyz.

    Check the address for typing errors such as ww.example.com instead of www.example.com
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

how to resolve this?

**Comment by danog** [comment]
Fixed
