### ISSUE TITLE
sendmessage method on my backend server

### ISSUE THREAD

**Issue by Maverick1983** [pwrtelegram/pwrtelegram#44]
I have this error:

\danog\MadelineProto\Exception: Undefined offset: 2 in /home/bot/api/vendor/danog/madelineproto/src/danog/MadelineProto/MTProto.php:641

**Comment by danog** [comment]
I need the TL trace

**Comment by Maverick1983** [comment]
TL Trace (YOU ABSOLUTELY MUST READ THE TEXT BELOW): MTProto.php(641): ExceptionErrorHandler(8,"Undefined offset: 2","\/home\/telegram\/api\/vendor\/danog\/madelineproto\/src\/danog\/MadelineProto\/MTProto.php",641,{"datacenter":2}) CallHandler.php(206):	close_and_reopen(2) MTProto.php(240): method_call("help.getNearestDc",[],{"datacenter":2}) Serializable.php(35):	___construct({"logger":{"logger":1},"pwr":{"pwr":true,"db_token":"","strict":true},"app_info":{"api_id":6,"api_hash":"eb06d4abfb49dc3eeb1aeb98ae0f581e"},"connection_settings":{"all":{"test_mode":false}}}) API.php(76): __construct({"logger":{"logger":1},"pwr":{"pwr":true,"db_token":"","strict":true},"app_info":{"api_id":6,"api_hash":"eb06d4abfb49dc3eeb1aeb98ae0f581e"},"connection_settings":{"all":{"test_mode":false}}}) Serializable.php(35):	___construct({"logger":{"logger":1},"pwr":{"pwr":true,"db_token":","strict":true},"app_info":{"api_id":6,"api_hash":"eb06d4abfb49dc3eeb1aeb98ae0f581e"},"connection_settings":{"all":{"test_mode":false}}}) Main.php(140): __construct({"logger":{"logger":1},"pwr":{"pwr":true,"db_token":"","strict":true},"app_info":{"api_id":6,"api_hash":"eb06d4abfb49dc3eeb1aeb98ae0f581e"},"connection_settings":{"all":{"test_mode":false}}}) index.php(38): __construct()

**Comment by danog** [comment]
Fixed
