### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by GooG2e** [pwrtelegram/pwrtelegram#46]
Hello!
I have tried to upload video with streaming_support=True via official telegram bot api and via pwrtelegram.
With telegram api video is streaming and everything is well but with pwrtelegram i have a problem - streaming is not enabled..

**Comment by GooG2e** [comment]
Still not working with last update while send video via PWRTelegram API

**Comment by danog** [comment]
@GooG2e I haven't implemented this in pwrtelegram yet

**Comment by danog** [comment]
I have now implemented this
