### ISSUE TITLE
Api issue

### ISSUE THREAD

**Issue by mrmmg** [pwrtelegram/pwrtelegram#48]
Hi
I want  use api.pwrtelegram.xyz but when i want to login with my phone number error 502 is showing to me.

DETALISE

Error 502 Ray ID: 4138edb79ea82708 • 2018-04-30 09:19:46 UTC

please solve this problem

**Comment by danog** [comment]
I suggest you use madelineproto.xyz instead, it's much more stable and much faster than pwrtelegram.
