### ISSUE TITLE
Error: This peer is not present in the internal peer database 

### ISSUE THREAD

**Issue by rad96** [pwrtelegram/pwrtelegram#50]
Receiving error
`This peer is not present in the internal peer database on line 369 of PeerHandler.php`
on method /bot(token)/sendDocument?chat_id=(id)&document=(file_id)

Any way i can fix that?

**Comment by rad96** [comment]
fixed it with using an nickname instead of chat_id, but i think that error is not normal

**Comment by danog** [comment]
It actually is normal, since the API can't use the ID of peers not yet present in the internal database (not yet met in any group/chat).
