### ISSUE TITLE
download with resume

### ISSUE THREAD

**Issue by ShahramCodeDeveloper** [pwrtelegram/pwrtelegram#51]
hello guys,

I did the resume direct link feature, but  when resume downloaded file after complete is correpted!

`            set_time_limit(0);
            ini_set('display_errors', 1);

            function no_cache($status, $wut)
	{
		    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
		    header('Cache-Control: post-check=0, pre-check=0', false);
		    header('Pragma: no-cache');
		    http_response_code($status);
		    echo $wut;
		    die;
	}

            if ($_SERVER['REQUEST_URI'] == '/') {
                header("HTTP/1.1 418 I'm a teapot");
                //analytics(true, '/', null, $dbuser, $dbpassword);
                exit('<html><h1>418 I&apos;m a teapot.</h1><br><p>My little teapot, my little teapot, oooh oooh oooh oooh...</p></html>');
            }
            try {
                $servefile = $_SERVER['REQUEST_METHOD'] !== 'HEAD';
                if (isset($_SERVER['HTTP_RANGE'])) {
                    $range = explode('=', $_SERVER['HTTP_RANGE'], 2);
                    if (count($range) == 1) {
                        $range[1] = '';
                    }
                    list($size_unit, $range_orig) = $range;
                    if ($size_unit == 'bytes') {
                        //multiple ranges could be specified at the same time, but for simplicity only serve the first range
                        //http://tools.ietf.org/id/draft-ietf-http-range-retrieval-00.txt
                        $list = explode(',', $range_orig, 2);
                        if (count($list) == 1) {
                            $list[1] = '';
                        }
                        list($range, $extra_ranges) = $list;
                    } else {
                        $range = '';
                        no_cache(416, '<html><body><h1>416 Requested Range Not Satisfiable.</h1><br><p>Could not use selected range.</p></body></html>');
                    }
                } else {
                    $range = '';
                }
                $listseek = explode('-', $range, 2);
                if (count($listseek) == 1) {
                    $listseek[1] = '';
                }
                list($seek_start, $seek_end) = $listseek;
                $seek_end = empty($seek_end) ? ($post['documentSize'] - 1) : min(abs(intval($seek_end)), $post['documentSize'] - 1);
                if (!empty($seek_start) && $seek_end < abs(intval($seek_start))) {
                    no_cache(416, '<html><body><h1>416 Requested Range Not Satisfiable.</h1><br><p>Could not use selected range.</p></body></html>');
                }
                $seek_start = empty($seek_start) ? 0 : abs(intval($seek_start));
                if ($servefile) {
                     //   no_cache(416, $seek_start.'|'.$seek_end);
                    if ($seek_start > 0 || $seek_end < $post['documentSize'] - 1) {
                        header('HTTP/1.1 206 Partial Content');
                        header('Content-Range: bytes '.$seek_start.'-'.$seek_end.'/'.$post['documentSize']);
                        header('Content-Length: '.($seek_end - $seek_start + 1));
                    } else {
                        header('Content-Length: '.$post['documentSize']);
                    }
                    header('Content-Type: application/x-rar');
                    header('Cache-Control: max-age=31556926;');
                    header('Content-Transfer-Encoding: Binary');
                    header('Accept-Ranges: bytes');
                    //header('Content-disposition: attachment: filename="'.basename($select['file_path']).'"');
                    //  no_cache(416, $content[0].'|'.$content[1]);
		$madeLineProto->download_to_stream($msg['messages'][0]['media']['document'], fopen('php://output', 'w'), null, $seek_start, $seek_end + 1);
                    //$madeLineProto->API->getting_state = false;
                    //$madeLineProto->API->store_db([], true);
                    //$madeLineProto->API->reset_session();
                } else {
                    if ($seek_start > 0 || $seek_end < $post['documentSize'] - 1) {
                        header('HTTP/1.1 206 Partial Content');
                        header('Content-Range: bytes '.$seek_start.'-'.$seek_end.'/'.$post['documentSize']);
                        header('Content-Length: '.($seek_end - $seek_start + 1));
                    } else {
                        header("HTTP/1.1 200 OK");
                        header('Content-Length: '.$post['documentSize']);
                    }
                    header('Content-Type: application/x-rar');
                    header('Cache-Control: max-age=31556926;');
                    header('Content-Transfer-Encoding: Binary');
                    header('Accept-Ranges: bytes');
                    //header('Content-disposition: attachment: filename="'.basename($select['file_path']).'"');
                }
            } catch (\danog\MadelineProto\ResponseException $e) {
                no_cache(500, 'error');
	}`

**Comment by ShahramCodeDeveloper** [comment]
internet download manager log:
log problem: C0:Check w_e_of_cn failed!
> Folder C:\Users\Shahram\AppData\Roaming\IDM\DwnlData\Shahram\xp_1824\ was created.
Rebuilding old downloaded file parts...
Connecting...
Windows 10.0
v6.32b6   Time: Fri Mar 15 16:26:18.69 2019 (1552654578 sec)
Url http://web.ecompany.ir /get/download/5/xp.rar
User : anonymous, password :xxx
Time: 1552654578.103
C0:gethost
C0:Found 207.244.66.44
Time: 1552654578.354
C0:Connecting...
C0:Checking connect, socket = 2804 
C0:Connect OK.
Time: 1552654578.635
C0:Send GET...
Time: 1552654578.685
C0:SC step12
C0:HTTP/1.1 200 OK
C0:Content-Type: application/x-rar
C0:Cache-Control: max-age=31556926;
C0:Content-Transfer-Encoding: Binary
C0:Accept-Ranges: bytes
C0:Content-Length: 1045714732
C0:Date: Fri, 15 Mar 2019 12:56:21 GMT
C0:Server: LiteSpeed
C0:Connection: close
C0:
C0:Receiving data...
Time: 1552654583.88
Optional connections, connecting...
time 1552654583
time 1552654583
Receiving data...
time 1552654585, speed 646185, downl 1491492 Bytes
time 1552654586, speed 721878, downl 2097152 Bytes
time 1552654586
C0:stratPos=0, endPos=1045714731, downloaded=2097152, posInCmpBuff3=0
C0:Disconnect.
Cancel by user.
Rebuilding old downloaded file parts...
Loading old localFileName - C:\Users\Shahram\AppData\Roaming\IDM\DwnlData\Shahram\xp_1824\xp.rar from registry
Loading old file size 1045714732 Bytes from registry
Rebuilding old downloaded files before resume.
This is the last chunk. End rebuilding.
Values counter in the registry subkey = 1
Connecting...
Windows 10.0
v6.32b6   Time: Fri Mar 15 16:26:28.470 2019 (1552654588 sec)
Url http://web.ecompany.ir /get/download/5/xp.rar
User : anonymous, password :xxx
Time: 1552654588.470
C0:gethost
C0:Found 207.244.66.44
Time: 1552654588.470
C0:Connecting...
first listitem id = 1919221760, startpos = 2097152, file C:\Users\Shahram\AppData\Roaming\IDM\DwnlData\Shahram\xp_1824\xp.rar, endpos = 0
C0:Checking connect, socket = 2544 
C0:Connect OK.
Time: 1552654588.677
C0:Send GET...
Time: 1552654588.683
C0:SC step12
C0:2097152-0, 2097088-
C0:HTTP/1.1 206 Partial Content
C0:Content-Range: bytes 2097088-1045714731/1045714732
C0:Content-Type: application/x-rar
C0:Cache-Control: max-age=31556926;
C0:Content-Transfer-Encoding: Binary
C0:Accept-Ranges: bytes
C0:Content-Length: 1043617644
C0:Date: Fri, 15 Mar 2019 12:56:31 GMT
C0:Server: LiteSpeed
C0:Connection: close
C0:
C0:Receiving data...
C0:Receiving data...
Time: 1552654593.383
Optional connections, connecting...
time 1552654593
time 1552654593
Receiving data...
C0:CWEOCOR 1559 OK
time 1552654595, speed 628987, downl 3495577 Bytes
time 1552654595
C0:stratPos=2097152, endPos=1045714731, downloaded=1398425, posInCmpBuff3=0
C0:Disconnect.
Cancel by user.
Rebuilding old downloaded file parts...
Loading old localFileName - C:\Users\Shahram\AppData\Roaming\IDM\DwnlData\Shahram\xp_1824\xp.rar from registry
Loading old file size 1045714732 Bytes from registry
Rebuilding old downloaded files before resume.
This is the last chunk. End rebuilding.
Values counter in the registry subkey = 1
Connecting...
Windows 10.0
v6.32b6   Time: Fri Mar 15 16:26:37.635 2019 (1552654597 sec)
Url http://web.ecompany.ir /get/download/5/xp.rar
User : anonymous, password :xxx
Time: 1552654597.635
C0:gethost
C0:Found 207.244.66.44
Time: 1552654597.635
C0:Connecting...
first listitem id = 92, startpos = 3495577, file C:\Users\Shahram\AppData\Roaming\IDM\DwnlData\Shahram\xp_1824\xp.rar, endpos = 0
C0:Checking connect, socket = 736 
C0:Connect OK.
Time: 1552654597.845
C0:Send GET...
Time: 1552654597.850
C0:SC step12
C0:3495577-0, 3495513-
C0:HTTP/1.1 206 Partial Content
C0:Content-Range: bytes 3495513-1045714731/1045714732
C0:Content-Type: application/x-rar
C0:Cache-Control: max-age=31556926;
C0:Content-Transfer-Encoding: Binary
C0:Accept-Ranges: bytes
C0:Content-Length: 1042219219
C0:Date: Fri, 15 Mar 2019 12:56:39 GMT
C0:Server: LiteSpeed
C0:Connection: close
C0:
C0:Receiving data...
C0:Receiving data...
Time: 1552654601.976
Optional connections, connecting...
time 1552654601
time 1552654601
Receiving data...
C0:Check w_e_of_cn failed!
C0:stratPos=3495577, endPos=1045714731, downloaded=0, posInCmpBuff3=0
C0:Disconnect.
C0:Connection is restarted...
Time: 1552654602.8
C0:gethost
C0:Found 207.244.66.44
Time: 1552654602.8
C0:Connecting...
C0:Send GET...
Time: 1552654602.227
C0:SC step12
C0:0-1045714731, 
C0:HTTP/1.1 200 OK
C0:Content-Type: application/x-rar
C0:Cache-Control: max-age=31556926;
C0:Content-Transfer-Encoding: Binary
C0:Accept-Ranges: bytes
C0:Content-Length: 1045714732
C0:Date: Fri, 15 Mar 2019 12:56:44 GMT
C0:Server: LiteSpeed
C0:Connection: close
C0:
C0:Receiving data...
time 1552654607, speed 18709, downl 161592 Bytes
time 1552654607
C0:stratPos=0, endPos=1045714731, downloaded=161592, posInCmpBuff3=0
C0:Disconnect.
Cancel by user.

**Comment by danog** [comment]
Try debugging with wget, instead; also please report this to the MadelineProto repo
