### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by Exlord** [pwrtelegram/pwrtelegram#54]
Hey I am using a node proxy to access telegram because its blocked in my country.

```
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;

const debug     = require('debug')('app');
const http      = require('http');
const httpProxy = require('http-proxy');

const proxy = httpProxy.createProxyServer({
  secure : false
});
proxy.on('error', function (e) {
  debug(e);
});

const server = http.createServer(function(req, res) {
  // You can define here your custom logic to handle the request
  // and then proxy the request.
  proxy.web(req, res, { target: 'https://deepapi.pwrtelegram.xyz', });
});

server.listen(3333);
```

it works fine with telegram, but when i use your url I am getting `Error: socket hang up` after waiting for some time ...

my server IP is `195.248.243.129`. Is my IP blocked or something?

**Comment by Exlord** [comment]
When I try to use it from my local dev using a proxy I am getting this error 
`Error: write EPROTO 12164:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1536:SSL alert number 80
`

**Comment by Exlord** [comment]
> 
> 
> When I try to use it from my local dev using a proxy I am getting this error
> `Error: write EPROTO 12164:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1536:SSL alert number 80 `

This seems to be a node.js bug(https://github.com/nodejs/node/issues/19359) .
Bummer ...
Have to get a new server to update my node :(

**Comment by danog** [comment]
Oki

**Comment by Exlord** [comment]
Ok, created a new server and updated nodejs (12.14.0) and openssl(1.1.1d) ... it seems the bug is on your side !

` Error: write EPROTO 140674774284160:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 80
`
` at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16) `

```
const debug     = require('debug')('app');
const https     = require('https');
const options = {
  hostname: 'deepapi.pwrtelegram.xyz',
  port    : 443,
  path    : '/bot329738389:AAH087APBjGPUPoAtXbzbv6NkkEepHGV-OQ/setWebHook',
  method  : 'GET',
  params  : { url: "https://3ce2f865.ngrok.io/bot329738389:AAH087APBjGPUPoAtXbzbv6NkkEepHGV-OQ" }
};

https.request(options, res => {
  debug(`statusCode: ${res.statusCode}`);

  res.on('data', d => {
    debug(d)
  })
}).on('error', error => {
  debug(error)
}).end();
```

It seems that you are using on older version of ssl/tls!!! Every ssl/tls checker I tested says you don't even have any ssl/tls!!!

**Comment by Exlord** [comment]
Ir seems that you are using on older version of ssl/tls!!!

**Comment by danog** [comment]
Welp this api was actually turned off three years ago, so there's that
You should use danog/MadelineProto now (https://t.me/MadelineProto)

**Comment by Exlord** [comment]
Seriously!!!!  Why is not this mentioned in the docs??? Why didn't you say anything before in the last comment???? I spend a week trying to figure out why is this not working!!!! Come onnnnnnnnnnnnnnnn man ...

**Comment by danog** [comment]
Aaaa sorry, technically api.pwrtelegram.xyz redirects to docs.madelineproto.xyz, and I thought this would be enough, anyways will update docs
