### ISSUE TITLE
Add chat joining method

### ISSUE THREAD

**Issue by danog** [pwrtelegram/pwrtelegram#7]
Add a joinChat method that accepts an invitation hash (channels and groups) or a username/user id (groups only, might work if bot is in channel?) that can be used to join groups or channels.
It will make use of the import_chat_link method to join if an invitation hash is provided, else the cli bot will join the group using the username/user id, add the bot (if possible) and then gtfo XDDDDDD

This is going to be so much fun.

**Comment by danog** [comment]
Can't do this anymore :(

**Comment by danog** [comment]
Or maybe I could implement just the joining using tg-Cli, adding the bot and gtfoing?

**Comment by NyaomiDEV** [comment]
@danog You can just insert My Little Pony GIFs everywhere and you're done

**Comment by ghost** [comment]
@danog Interessante...
Ma poi l'account che usi potrebbe finire in blacklists, tipo quella di IATA...
