### ISSUE TITLE
Make getuserprofilephotos work with bots and users that haven't contacted the bot yet.

### ISSUE THREAD

**Issue by danog** [pwrtelegram/pwrtelegram#9]
A nice feature would be to make getuserprofilephotos work with bots and users that haven't contacted the bot yet. Should be pretty easy to do with tg-cli.

**Comment by danog** [comment]
That can already be done xd

**Comment by alexilgenerale** [comment]
@danog A

**Comment by MarcoBuster** [comment]
@alexilgenerale What's happening?

**Comment by alexilgenerale** [comment]
@MarcoBuster Sorry,it was a test
